### ISSUE TITLE
Use of the featured image

### ISSUE THREAD

**Issue by laralfield** [bwdinc/simmer#11]
Right now, the featured image doesn't get a major "feature role" in the recpe card itself for Simmer recipes, and I think it should for every recipe published, regardless of the theme. 

To do this, I think we can set an uncropped thumbnail version to the right of the Ingredients section for any given recipe. It should never have a border or background for now (this should solve easy integration into any parent or child theme). If no featured image is included with a recipe, nothing appears. I think it should be nested to the right of the UL, not from the top of the Ingredients headline, to create a simple but effective design.

Let me know what you think :) I'm sure there are certain cases I'm forgetting about, etc...

**Comment by ChaseWiseman** [comment]
Yes, I agree about including the featured image somewhere within embedded recipes. I think we should play around with placement though, as adding it to the ingredients list could create conflicts down the line if we extend ingredients further with images, etc...

This will also need to work in tandem with the direction we go with #12 re: descriptions. It sounds like we need to decide how much information we want to include and where, as there are two main recipe views:

1. Single recipe (example.com/recipes/this-recipe/)
2. Embedded recipe within a blog post (links to single recipe)

My inclination is to leave the big stuff like detailed descriptions & images to blog posts, and keep recipes as to-the-point as possible, but that could change if there ends up being user feedback to the contrary.

I'll also be adding a new issue in a few minutes that will track the work that needs to be done to add a solid templating structure to Simmer, so that will certainly affect this issue.

**Comment by laralfield** [comment]
Yes. I'm thinking now, with #12, that when the feature image is included, it's featured only next to the excerpt, left or right nested. 

We can include the excerpt (#12) and the featured image then at the top of recipe cards, and include an option to turn this feature on or off. It will be on by default. (Automatically include featured images with all recipe excerpts). 

What do you think of this kind of direction?
