### ISSUE TITLE
Move ingredients & instructions to custom DB tables

### ISSUE THREAD

**Issue by ChaseWiseman** [bwdinc/simmer#36]
Back when Simmer was but a twinkle in our collective eye, recipe ingredients and instructions were thought to be best stored as post meta in associative arrays. After all, the information for each item was fairly simple: `amount`, `unit`, and `text`, or in the case of instructions, just `text`. It was a noble stance, one to keep the database schema as simple as possible and use the tools already provided by WordPress.

As these two recipe items become more complex and need more and more extendability to support future extensions, it's becoming clear that we need to rethink that stance. As such, I'm going to start the process of porting post meta ingredients and instructions over to their own custom database tables:

`_simmer_recipe_items`
`_simmer_recipe_itemmeta`

This will allow each recipe item to have its own unique ID and complex meta values, just like recipes themselves. We'll then build a meta API that mimics WordPress' own post meta API which will include functions like `simmer_add_recipe_item` and `simmer_update_recipe_item_meta`.

I had briefly considered saving recipe items as their own post type, but isn't the right fit as they have no titles or content and will be added/updated/deleted far more frequently than I think the `wp_posts` table is meant to handle. After this new API is finalized, we'll then need to go through and build an install & upgrade procedure to convert current Simmer users' data to the new schema so no one gets left behind.

One side benefit of this huge undertaking is that adding REST API support (#35)  will be much easier and can be done in tandem with this effort.

**Comment by laralfield** [comment]
🙌

This really solid strategy, and a great choice over the "post type" solution, it sounds like too. The schema change fix sounds great as well. This seems to also really work towards our goal of making Simmer as extendable and developer/software focused as possible.

Side note for the **content/the blog**: This would also make awesome blog post territory, if you want to jot down some "diary" type notes along the way so that we can shine some great light on the new REST API. Open to all ideas at all times ✏️ :)
